### ISSUE TITLE
Atom entry link

### ISSUE THREAD

**Issue by joksnet** [gnugat/gnugat.github.io#29]
Hi Loïc.

I read your blog using a feed reader and it's always difficult to follow the link for each entry, as it doesn't contains the full URL.

I don't know if is a problem with my feed reader (Claws) that doesn't read the base URL for all entries or just that Sculpin is not generating full URLs because missing configuration or other problem.

I will investigate within atom specification and my feed reader implementation.

**Comment by gnugat** [comment]
Hi Juan,

Thanks for reporting the issue, I'll also investigate on my side.

**Comment by gnugat** [comment]
I've found the issue: I needed to explicitely set `site.url` variable. Should be fixed now, thanks again!

**Comment by joksnet** [comment]
It worked! Thanks.
