### ISSUE TITLE
Blog broken on HTTPS

### ISSUE THREAD

**Issue by jdreesen** [gnugat/gnugat.github.io#32]
I'm using [HTTPS Everywhere](https://www.eff.org/https-everywhere) and thus being redirected to https://gnugat.github.io/ automatically. Sadly, since some days, your blog is broken when using HTTPS because the assets gets loaded via an absolute `http://` URL:

![broken-https](https://cloud.githubusercontent.com/assets/424602/12657745/38b67368-c605-11e5-8940-574bc8b8f227.png)

I'm new to sculpin and wasn't able to determine where `site.url` is defined, otherwise this would've been a pull request ;)

**Comment by gnugat** [comment]
Hi @jdreesen thanks for reporting the issue. I'll check Scuplin to know how this could be fixed.

**Comment by gnugat** [comment]
Hey @jdreesen, I think I got what went wrong (I'll just need to set the site_url to HTTPS in sculpin production configuration). Should be fixed with the next publication (wednesday 10th of February if all is fine).

**Comment by jdreesen** [comment]
I'm looking forward to it :)

**Comment by gnugat** [comment]
It's been deployed, but we get one error:

```
Mixed Content: The page at 'https://gnugat.github.io/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Raleway:400,300,600'. This request has been blocked; the content must be served over HTTPS.
```

It's an easy fix and will be available at the next publication (wednesday next week). Thanks again for reporting the issue

**Comment by jdreesen** [comment]
I confirm that it works with HTTPS now, except for the custom font. 
However, it already looks much better now, thx :)

**Comment by gnugat** [comment]
@jdreesen It should now fixed, could you confirm?

**Comment by jdreesen** [comment]
Looks good! :)
