### ISSUE TITLE
Continue the idea

### ISSUE THREAD

**Issue by lucianodelucchi** [gnugat/gnugat.github.io#34]
There is something missing, may be you were interrupted in the middle of your writing :)

Please take a look at [this line](https://github.com/gnugat/gnugat.github.io/blob/a3bc4f6b047d047c6a79466d38762b5e91fe5cca/2016/02/10/ultimate-symfony-event-dispatcher.html#L223) on your nice blog post.

**Comment by gnugat** [comment]
Hi @lucianodelucchi, thanks for reporting this. I'll try to remember what I meant and republish today.

It's probably related to the fact that `kernel.finish_request` is executed before sending the response, as opposed to `kernel.terminate` which is executed after (so the first one slows down the Response and not the second one).

**Comment by gnugat** [comment]
It's now fixed, thanks for reporting the issue (I've removed the paragraph altogether).
