### ISSUE TITLE
Improve alternatives description

### ISSUE THREAD

**Issue by gnugat** [gnugat/gnugat.github.io#48]
The section describing ReactPHP is too confusing. Expand it to better explain the differences between PHPFastCGI, Aerys, IcicleIo and ReactPHP.

See:

* first comment about it here: https://github.com/gnugat/gnugat.github.io/commit/68b650fd9492103e1190ae647580bc09034cc712#commitcomment-17087823
* second comments here: https://twitter.com/kelunik/status/720349186495909888?s=09

**Comment by kelunik** [comment]
Why did this ping me? Because of my username in an URL?

**Comment by gnugat** [comment]
Yes kind of, that's due to a mistake from my side when originally creating the issue, which I've edited since then. Sorry for the inconvenience, you can unsubscribe from its notifications.
Would you like to help me write a better description for Aerys? This issue is about improving the [article](https://gnugat.github.io/2016/04/13/super-speed-sf-react-php.html) we discussed on Twitter.

**Comment by gnugat** [comment]
Fixed in #51
