### ISSUE TITLE
Can you tell about no longer maintained projects

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [gnugat/gnugat.github.io#71]
https://github.com/synox/disposable-mailbox is using https://github.com/gnugat-legacy/PronounceableWord but in heroku it says the git is outdated. any way to get rid of this error.

**Comment by gnugat** [comment]
Hi @ParveenBhadooOfficial, as you can see on [packagist](https://packagist.org/packages/gnugat/pronounceableword), the PronounceableWord package is marked as "abandoned and no longer maintained".

I can add a mention on the git repo and on my blog to make it clearer.

**Comment by ParveenBhadooOfficial** [comment]
I understand sir, but i don't have an alternative to it and if i can still use the package. Just one answer and it'll be done.

**Comment by ParveenBhadooOfficial** [comment]
Can i clone or remake it so it doesn't shows as abandoned in that project.

**Comment by gnugat** [comment]
I'm afraid there's not fix I can provide for abandoned packages, all I can suggest is try and find an alternative (eg searching "markov" or similar on packagist), or fork this repo and create a new package.

Good luck!
